#pragma once

//glfw3.h key codes
#define STLR_KEY_ESCAPE             256
#define STLR_KEY_ENTER              257
#define STLR_KEY_TAB                258
#define STLR_KEY_BACKSPACE          259
#define STLR_KEY_INSERT             260
#define STLR_KEY_DELETE             261
#define STLR_KEY_RIGHT              262
#define STLR_KEY_LEFT               263
#define STLR_KEY_DOWN               264
#define STLR_KEY_UP                 265
#define STLR_KEY_PAGE_UP            266
#define STLR_KEY_PAGE_DOWN          267
#define STLR_KEY_HOME               268
#define STLR_KEY_END                269
#define STLR_KEY_CAPS_LOCK          280
#define STLR_KEY_SCROLL_LOCK        281
#define STLR_KEY_NUM_LOCK           282
#define STLR_KEY_PRINT_SCREEN       283
#define STLR_KEY_PAUSE              284
#define STLR_KEY_F1                 290
#define STLR_KEY_F2                 291
#define STLR_KEY_F3                 292
#define STLR_KEY_F4                 293
#define STLR_KEY_F5                 294
#define STLR_KEY_F6                 295
#define STLR_KEY_F7                 296
#define STLR_KEY_F8                 297
#define STLR_KEY_F9                 298
#define STLR_KEY_F10                299
#define STLR_KEY_F11                300
#define STLR_KEY_F12                301
#define STLR_KEY_F13                302
#define STLR_KEY_F14                303
#define STLR_KEY_F15                304
#define STLR_KEY_F16                305
#define STLR_KEY_F17                306
#define STLR_KEY_F18                307
#define STLR_KEY_F19                308
#define STLR_KEY_F20                309
#define STLR_KEY_F21                310
#define STLR_KEY_F22                311
#define STLR_KEY_F23                312
#define STLR_KEY_F24                313
#define STLR_KEY_F25                314
#define STLR_KEY_KP_0               320
#define STLR_KEY_KP_1               321
#define STLR_KEY_KP_2               322
#define STLR_KEY_KP_3               323
#define STLR_KEY_KP_4               324
#define STLR_KEY_KP_5               325
#define STLR_KEY_KP_6               326
#define STLR_KEY_KP_7               327
#define STLR_KEY_KP_8               328
#define STLR_KEY_KP_9               329
#define STLR_KEY_KP_DECIMAL         330
#define STLR_KEY_KP_DIVIDE          331
#define STLR_KEY_KP_MULTIPLY        332
#define STLR_KEY_KP_SUBTRACT        333
#define STLR_KEY_KP_ADD             334
#define STLR_KEY_KP_ENTER           335
#define STLR_KEY_KP_EQUAL           336
#define STLR_KEY_LEFT_SHIFT         340
#define STLR_KEY_LEFT_CONTROL       341
#define STLR_KEY_LEFT_ALT           342
#define STLR_KEY_LEFT_WINDOWS        343
#define STLR_KEY_RIGHT_SHIFT        344
#define STLR_KEY_RIGHT_CONTROL      345
#define STLR_KEY_RIGHT_ALT          346
#define STLR_KEY_RIGHT_SUPER        347
#define STLR_KEY_MENU               348

